all:
  vars:
    ansible_user: vagrant
  children:
    dev:
      hosts:
        '127.0.0.1':
          ansible_ssh_port: 2222
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/ota-vagrant
          base_url: http://ota.local
          enable_https: false
