all:
  children:
    production:
      hosts:
        51.89.227.200:
          ansible_user: debian
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
          ansible_python_interpreter: /usr/bin/python3
          base_url: http://51.89.227.200
          enable_https: true
          ports:
            "contribute.opentermsarchive.org": 7023
            "contribute.preprod.opentermsarchive.org": 7024
            "api.preprod.opentermsarchive.org": 7012
            "api.opentermsarchive.org": 7011
          certbot_create_if_missing: true
          certbot_create_method: standalone
          certbot_admin_email: martin.ratinaud@beta.gouv.fr
          certbot_auto_renew: true
          certbot_auto_renew_user: "{{ ansible_user }}"
          certbot_auto_renew_hour: "4"
          certbot_auto_renew_minute: "30"
          certbot_auto_renew_options: "--no-random-sleep-on-renew --nginx --nginx-ctl /usr/sbin/nginx --nginx-server-root /etc/nginx/"
          certbot_certs:
            - domains:
                - "contribute.opentermsarchive.org"
            - domains:
                - "contribute.preprod.opentermsarchive.org"
            - domains:
                - "api.preprod.opentermsarchive.org"
            - domains:
                - "api.opentermsarchive.org"
